{{- if (not .Values.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASS: {{ .Values.postgres.password | b64enc | quote }}
  POSTGRES_URI_ARGS: {{ .Values.postgres.uri_args | b64enc | quote }}
  POSTGRES_CLOUD_PROVIDER: {{ .Values.postgres.cloud_provider | b64enc | quote }}
  POSTGRES_DEFAULT_DATABASE: {{ .Values.postgres.default_database | b64enc | quote }}
{{- end }}
