apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: operators

resources:
- crds/db.movetokube.com_postgres_crd.yaml
- crds/db.movetokube.com_postgresusers_crd.yaml
- operator.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
