apiVersion: v2
name: ext-postgres-operator
description: |
  A Helm chart for the External Postgres operator

  helm repo add ext-postgres-operator https://movetokube.github.io/postgres-operator/
  helm upgrade --install -n operators ext-postgres-operator  ext-postgres-operator/ext-postgres-operator

type: application

version: 2.3.0
appVersion: "2.4.0"
