name: Publish Operator

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate Docker Tag
        run: |
          echo ${{ github.ref }} | cut -d '/' -f 3 > DOCKER_TAG
      - name: Build and push container image
        run: |
          docker build --file build/Dockerfile.dist --tag ghcr.io/movetokube/postgres-operator:$(cat DOCKER_TAG) --tag movetokube/postgres-operator:$(cat DOCKER_TAG) .
          docker tag ghcr.io/movetokube/postgres-operator:$(cat DOCKER_TAG) ghcr.io/movetokube/postgres-operator:latest
          docker tag movetokube/postgres-operator:$(cat DOCKER_TAG) movetokube/postgres-operator:latest
         
          docker login ghcr.io --username USERNAME --password ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/movetokube/postgres-operator:$(cat DOCKER_TAG)
          docker push ghcr.io/movetokube/postgres-operator:latest
          
          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_TOKEN }}
          docker push movetokube/postgres-operator:$(cat DOCKER_TAG)
          docker push movetokube/postgres-operator:latest


